### ISSUE TITLE
pls add a icon

### ISSUE THREAD

**Issue by Hackerdash** [UPSC-Hindi/flutter-app#32]

**Comment by Hackerdash** [comment]
![Image](https://user-images.githubusercontent.com/32676675/208603943-7c459bc2-98ad-4b6e-865e-be1527835ba9.png)

**Comment by Hackerdash** [comment]
![Image](https://user-images.githubusercontent.com/32676675/208604104-b7b207cd-4dab-4ae6-83c2-54defe099342.png)

plss add the image

**Comment by SDnivog** [comment]
@Hackerdash Please find the icon url

https://storage-upschindi.s3.ap-south-1.amazonaws.com/data/images/book_pan.png
